version: "3.1"

services:
    db:
        image: mysql:8.0
        # build: db
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        secrets:
            - db_root_password
            - db_database
        environment:
            - TZ=CET
            - MYSQL_DATABASE_FILE=/run/secrets/db_database
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
        networks:
            web-db:
            admin-db:
        volumes:
            - wp-db:/var/lib/mysql

    web:
        image: wp:php8-apache-buster
        build: web
        restart: always
        secrets:
            - db_root_password
            - db_database
        environment:
            - TZ=CET
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_NAME_FILE=/run/secrets/db_database
            - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_root_password
            - WP_DEBUG=true
        networks:
            - web-db
        ports:
            - 58080:80
        volumes:
            - C:\Dev\wordpress\web\src:/var/www/html
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin:5.0-apache
        secrets:
            - db_root_password
        environment:
            - TZ=CET
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD_FILE=/run/secrets/db_root_password
        ports:
            - 55081:80
        networks:
            - admin-db
        depends_on:
            - db

networks:
    web-db:
    admin-db:

volumes:
    wp-db:

secrets:
    db_root_password:
        file: ./db/secrets/root_password
    db_database:
        file: ./db/secrets/database
